default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.6

images:
  - docker.io/bitnami/etcd:3.5.4-debian-11-r14
  - docker.io/apache/apisix-dashboard:3.0.0-alpine
  - docker.io/busybox:1.28
